CREATE DATABASE wordpress;
CREATE USER 'admin'@'%' IDENTIFIED BY 'pw_admin';
CREATE USER 'user1'@'%' IDENTIFIED BY "pw_user1";
CREATE USER 'user2'@'%' IDENTIFIED BY "pw_user2";
CREATE USER 'user3'@'%' IDENTIFIED BY "pw_user3";
GRANT ALL PRIVILEGES ON wordpress.* TO 'admin'@'%';
GRANT SELECT ON wordpress.* TO 'user1'@'%';
GRANT SELECT ON wordpress.* TO 'user2'@'%';
GRANT SELECT ON wordpress.* TO 'user3'@'%';
FLUSH PRIVILEGES;
