apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpma-deployment
  labels:
    app: phpma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpma
  template:
    metadata:
      labels:
        app: phpma
    spec:
      containers:
      - name: phpma
        image: my-phpma
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: phpmyadmin
  selector:
      app: phpma