apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my-ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name : ftps
        livenessProbe:
          exec:
            command:
              - pgrep
              - vsftpd
          initialDelaySeconds: 3
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
    name: ftps
spec:
    type: LoadBalancer
    ports:
    - name: ftps
      port: 21
    - name: ftps-passive
      port: 30020
    selector:
        app: ftps